---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - pod_kaspa_explorer

- name: check service pod_kaspa_explorer
  shell: "{{command_cmd_check_service_pod_kaspa_explorer}}"
  register: register_check_service_pod_kaspa_explorer
  changed_when: (register_check_service_pod_kaspa_explorer.rc == 0)
  failed_when: (register_check_service_pod_kaspa_explorer.rc > 1)
  check_mode: False
  tags:
    - pod_kaspa_explorer

- name: stop service pod_kaspa_explorer
  service:
    state: stopped
    enabled: False
    name: "{{service_name_pod_kaspa_explorer}}"
    daemon_reload: True
  when: (register_check_service_pod_kaspa_explorer.rc == 0)
  tags:
    - pod_kaspa_explorer

- name: remove file pod_kaspa_explorer.nft
  file:
    state: absent
    path: "{{file_dst_pod_kaspa_explorer_nft}}"
  notify: reload nftables
  tags:
    - pod_kaspa_explorer

- name: remove file pod_kaspa_explorer-kaspa-explorer.cfg
  file:
    state: absent
    path: "{{file_dst_pod_kaspa_explorer_kaspa_explorer_cfg}}"
  notify: reload monit
  tags:
    - pod_kaspa_explorer

- name: remove file pod_kaspa_explorer_etc.dir
  file:
    state: absent
    path: "{{file_dst_pod_kaspa_explorer_etc_dir}}"
  tags:
    - pod_kaspa_explorer

- name: remove file pod_kaspa_explorer.default
  file:
    state: absent
    path: "{{file_dst_pod_kaspa_explorer_default}}"
  tags:
    - pod_kaspa_explorer

- name: remove file pod_kaspa_explorer.service
  file:
    state: absent
    path: "{{file_dst_pod_kaspa_explorer_service}}"
  tags:
    - pod_kaspa_explorer
