---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - lnd

- name: create file lnd.default
  template:
    src: "{{file_src_lnd_default}}"
    dest: "{{file_dst_lnd_default}}"
    mode: "{{file_mode_lnd_default}}"
    owner: "{{file_owner_lnd_default}}"
    group: "{{file_group_lnd_default}}"
  tags:
    - lnd

- name: create file lnd.conf
  template:
    src: "{{file_src_lnd_conf}}"
    dest: "{{file_dst_lnd_conf}}"
    mode: "{{file_mode_lnd_conf}}"
    owner: "{{file_owner_lnd_conf}}"
    group: "{{file_group_lnd_conf}}"
  tags:
    - lnd

- name: create file lnd.cfg
  template:
    src: "{{file_src_lnd_cfg}}"
    dest: "{{file_dst_lnd_cfg}}"
    mode: "{{file_mode_lnd_cfg}}"
    owner: "{{file_owner_lnd_cfg}}"
    group: "{{file_group_lnd_cfg}}"
  notify: reload service monit
  when: (lnd_monitor_monit_state is match('true|yes|enable'))
  tags:
    - lnd

- name: stop service lnd
  service:
    state: 'stopped'
    enabled: 'no'
    name: "{{service_name_lnd}}"
    daemon_reload: 'yes'
  tags:
    - lnd
