---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - lnd

- name: create file lnd.default
  template:
    src: "{{file_src_lnd_default}}"
    dest: "{{file_dst_lnd_default}}"
    mode: "{{file_mode_lnd_default}}"
    owner: "{{file_owner_lnd_default}}"
    group: "{{file_group_lnd_default}}"
  tags:
    - lnd

- name: create file lnd.conf
  template:
    src: "{{file_src_lnd_conf}}"
    dest: "{{file_dst_lnd_conf}}"
    mode: "{{file_mode_lnd_conf}}"
    owner: "{{file_owner_lnd_conf}}"
    group: "{{file_group_lnd_conf}}"
  tags:
    - lnd

- name: remove file lnd.cfg
  file:
    state: absent
    path: "{{file_dst_lnd_cfg}}"
  notify: reload service monit
  tags:
    - lnd

- name: create file lnd.nft
  template:
    src: "{{file_src_lnd_nft}}"
    dest: "{{file_dst_lnd_nft}}"
    mode: "{{file_mode_lnd_nft}}"
    owner: "{{file_owner_lnd_nft}}"
    group: "{{file_group_lnd_nft}}"
  notify: reload service nftables
  when: (lnd_nftables_state == True)
  tags:
    - lnd

- name: remove file lnd.nft
  file:
    state: absent
    path: "{{file_dst_lnd_nft}}"
  notify: reload service nftables
  when: (lnd_nftables_state == False)
  tags:
    - lnd

- name: stop service lnd
  service:
    state: stopped
    enabled: False
    name: "{{service_name_lnd}}"
    daemon_reload: True
  tags:
    - lnd
