---

- name: include variables
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_distribution_major_version}}.yml"
      - 'vars/main.yml'
      errors: 'ignore'
  tags:
    - lnd

- name: remove user lnd
  user:
    state: 'absent'
    name: "{{user_name_lnd}}"
    remove: "{{user_home_remove_lnd}}"
    force: "{{user_home_force_lnd}}"
  tags:
    - lnd

- name: remove group lnd
  group:
    state: 'absent'
    name: "{{group_name_lnd}}"
  tags:
    - lnd

- name: remove file lnd.cfg
  file:
    state: 'absent'
    path: "{{file_dst_lnd_cfg}}"
  notify: reload service monit
  tags:
    - lnd

- name: remove file lnd.service
  file:
    state: 'absent'
    path: "{{file_dst_lnd_service}}"
  tags:
    - lnd

- name: remove file lnd.default
  file:
    state: 'absent'
    path: "{{file_dst_lnd_default}}"
  tags:
    - lnd

- name: remove file lnd_app.dir
  file:
    state: 'absent'
    path: "{{file_dst_lnd_app_dir}}"
  tags:
    - lnd

- name: remove file lnd_src.dir
  file:
    state: 'absent'
    path: "{{file_dst_lnd_src_dir}}"
  tags:
    - lnd
