---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - pod_bitcoin_core

- name: create file pod_bitcoin_core.yaml
  template:
    src: "{{file_src_pod_bitcoin_core_yaml}}"
    dest: "{{file_dst_pod_bitcoin_core_yaml}}"
    mode: "{{file_mode_pod_bitcoin_core_yaml}}"
    owner: "{{file_owner_pod_bitcoin_core_yaml}}"
    group: "{{file_group_pod_bitcoin_core_yaml}}"
  tags:
    - pod_bitcoin_core

- name: create file pod_bitcoin_core.default
  template:
    src: "{{file_src_pod_bitcoin_core_default}}"
    dest: "{{file_dst_pod_bitcoin_core_default}}"
    mode: "{{file_mode_pod_bitcoin_core_default}}"
    owner: "{{file_owner_pod_bitcoin_core_default}}"
    group: "{{file_group_pod_bitcoin_core_default}}"
  tags:
    - pod_bitcoin_core

- name: remove file pod_bitcoin_core-bitcoin-core.cfg
  file:
    state: absent
    path: "{{file_dst_pod_bitcoin_core_bitcoin_core_cfg}}"
  notify: reload service monit
  tags:
    - pod_bitcoin_core

- name: stop service pod_bitcoin_core
  service:
    state: stopped
    enabled: False
    name: "{{service_name_pod_bitcoin_core}}"
    daemon_reload: True
  tags:
    - pod_bitcoin_core
