---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - pod_bitcoin_core

- name: copy file subuid
  copy:
    src: "{{file_src_subuid}}"
    dest: "{{file_dst_subuid}}"
    mode: "{{file_mode_subuid}}"
    owner: "{{file_owner_subuid}}"
    group: "{{file_group_subuid}}"
  tags:
    - pod_bitcoin_core

- name: copy file subgid
  copy:
    src: "{{file_src_subgid}}"
    dest: "{{file_dst_subgid}}"
    mode: "{{file_mode_subgid}}"
    owner: "{{file_owner_subgid}}"
    group: "{{file_group_subgid}}"
  tags:
    - pod_bitcoin_core

- name: create group pod_bitcoin_core
  group:
    state: present
    name: "{{group_name_pod_bitcoin_core}}"
    gid: "{{group_gid_pod_bitcoin_core}}"
    system: "{{group_system_pod_bitcoin_core}}"
  tags:
    - pod_bitcoin_core

- name: create user pod_bitcoin_core
  user:
    state: present
    name: "{{user_name_pod_bitcoin_core}}"
    comment: "{{user_comment_pod_bitcoin_core}}"
    uid: "{{user_uid_pod_bitcoin_core}}"
    group: "{{user_group_pod_bitcoin_core}}"
    groups: "{{user_groups_pod_bitcoin_core}}"
    append: "{{user_append_pod_bitcoin_core}}"
    createhome: "{{user_home_create_pod_bitcoin_core}}"
    move_home: "{{user_home_move_pod_bitcoin_core}}"
    remove: "{{user_home_remove_pod_bitcoin_core}}"
    force: "{{user_home_force_pod_bitcoin_core}}"
    password: "{{user_password_pod_bitcoin_core}}"
    update_password: "{{user_password_update_pod_bitcoin_core}}"
    shell: "{{user_shell_pod_bitcoin_core}}"
    system: "{{user_system_pod_bitcoin_core}}"
  register: register_create_user_pod_bitcoin_core
  tags:
    - pod_bitcoin_core

- name: loginctl enable-linger
  shell: "{{command_cmd_loginctl_enable_linger}}"
  check_mode: False
  when: register_create_user_pod_bitcoin_core.changed
  tags:
    - pod_bitcoin_core

- name: create file pod_bitcoin_core_etc.dir
  file:
    state: directory
    path: "{{file_dst_pod_bitcoin_core_etc_dir}}"
    mode: "{{file_mode_pod_bitcoin_core_etc_dir}}"
    owner: "{{file_owner_pod_bitcoin_core_etc_dir}}"
    group: "{{file_group_pod_bitcoin_core_etc_dir}}"
  tags:
    - pod_bitcoin_core

- name: create file opt.dir
  file:
    state: directory
    path: "{{file_dst_opt_dir}}"
    mode: "{{file_mode_opt_dir}}"
    owner: "{{file_owner_opt_dir}}"
    group: "{{file_group_opt_dir}}"
  tags:
    - pod_bitcoin_core

- name: create file pod_bitcoin_core_opt.dir
  file:
    state: directory
    path: "{{file_dst_pod_bitcoin_core_opt_dir}}"
    mode: "{{file_mode_pod_bitcoin_core_opt_dir}}"
    owner: "{{file_owner_pod_bitcoin_core_opt_dir}}"
    group: "{{file_group_pod_bitcoin_core_opt_dir}}"
  tags:
    - pod_bitcoin_core

- name: create file bitcoin-core_db.dir
  file:
    state: directory
    path: "{{file_dst_bitcoin_core_db_dir}}"
    mode: "{{file_mode_bitcoin_core_db_dir}}"
    owner: "{{file_owner_bitcoin_core_db_dir}}"
    group: "{{file_group_bitcoin_core_db_dir}}"
  tags:
    - pod_bitcoin_core

- name: create file pod_bitcoin_core.service
  template:
    src: "{{file_src_pod_bitcoin_core_service}}"
    dest: "{{file_dst_pod_bitcoin_core_service}}"
    mode: "{{file_mode_pod_bitcoin_core_service}}"
    owner: "{{file_owner_pod_bitcoin_core_service}}"
    group: "{{file_group_pod_bitcoin_core_service}}"
  tags:
    - pod_bitcoin_core

- name: stat file monit.d
  stat:
    path: "{{file_dst_monit_d}}"
  register: register_monit_d
  when: (pod_bitcoin_core_monitor_monit_state == True)
  tags:
    - pod_bitcoin_core

- name: create file monit.d
  file:
    state: directory
    path: "{{file_dst_monit_d}}"
    mode: "{{file_mode_monit_d}}"
    owner: "{{file_owner_monit_d}}"
    group: "{{file_group_monit_d}}"
  when: (pod_bitcoin_core_monitor_monit_state == True) and (register_monit_d.stat.exists == False)
  tags:
    - pod_bitcoin_core

- name: stat file nftables.d
  stat:
    path: "{{file_dst_nftables_d}}"
  register: register_nftables_d
  when: (pod_bitcoin_core_nftables_state == True)
  tags:
    - pod_bitcoin_core

- name: create file nftables.d
  file:
    state: directory
    path: "{{file_dst_nftables_d}}"
    mode: "{{file_mode_nftables_d}}"
    owner: "{{file_owner_nftables_d}}"
    group: "{{file_group_nftables_d}}"
  when: (pod_bitcoin_core_nftables_state == True) and (register_nftables_d.stat.exists == False)
  tags:
    - pod_bitcoin_core
