---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - pod_bitcoin_core

- name: check service pod_bitcoin_core
  shell: "{{command_cmd_check_service_pod_bitcoin_core}}"
  register: register_check_service_pod_bitcoin_core
  changed_when: (register_check_service_pod_bitcoin_core.rc == 0)
  failed_when: (register_check_service_pod_bitcoin_core.rc > 1)
  check_mode: False
  tags:
    - pod_bitcoin_core

- name: stop service pod_bitcoin_core
  service:
    state: stopped
    enabled: False
    name: "{{service_name_pod_bitcoin_core}}"
    daemon_reload: True
  when: (register_check_service_pod_bitcoin_core.rc == 0)
  tags:
    - pod_bitcoin_core

- name: remove file pod_bitcoin_core.nft
  file:
    state: absent
    path: "{{file_dst_pod_bitcoin_core_nft}}"
  notify: reload nftables
  tags:
    - pod_bitcoin_core

- name: remove file pod_bitcoin_core-bitcoin-core.cfg
  file:
    state: absent
    path: "{{file_dst_pod_bitcoin_core_bitcoin_core_cfg}}"
  notify: reload monit
  tags:
    - pod_bitcoin_core

- name: remove file pod_bitcoin_core_etc.dir
  file:
    state: absent
    path: "{{file_dst_pod_bitcoin_core_etc_dir}}"
  tags:
    - pod_bitcoin_core

- name: remove file pod_bitcoin_core.default
  file:
    state: absent
    path: "{{file_dst_pod_bitcoin_core_default}}"
  tags:
    - pod_bitcoin_core

- name: remove file pod_bitcoin_core.service
  file:
    state: absent
    path: "{{file_dst_pod_bitcoin_core_service}}"
  tags:
    - pod_bitcoin_core
