---

{{ansible_managed|comment(decoration='#')}}

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: btcd
  name: pod_btcd
spec:
  containers:
  - name: btcd
    image: {{pod_btcd_registry_address}}/btcd:{{pod_btcd_btcd_version}}
    ports:
{% if (pod_btcd_btcd_environment_variables.LISTEN is defined) %}
    - name: btcd-network
      containerPort: {{pod_btcd_btcd_environment_variables.LISTEN.rsplit(':', 1)[-1]}}
      hostPort: {{pod_btcd_btcd_environment_variables.LISTEN.rsplit(':', 1)[-1]}}
      protocol: TCP
{% endif %}
{% if (pod_btcd_btcd_environment_variables.RPCLISTEN is defined) %}
    - name: btcd-rpc
      containerPort: {{pod_btcd_btcd_environment_variables.RPCLISTEN.rsplit(':', 1)[-1]}}
      hostPort: {{pod_btcd_btcd_environment_variables.RPCLISTEN.rsplit(':', 1)[-1]}}
      protocol: TCP
{% endif %}
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: {{pod_btcd_btcd_read_only_root_filesystem|lower}}
      runAsGroup: 10000
      runAsUser: 10000
      seLinuxOptions:
        type: spc_t
    volumeMounts:
    - name: btcd-db
      mountPath: /home/btcd/.btcd
    workingDir: /
    env:
{% if not (pod_btcd_btcd_environment_variables == {}) %}
{% for key, value in pod_btcd_btcd_environment_variables.items() %}
    - name: {{key|upper}}
      value: '{{value}}'
{% endfor %}
{% endif %}

  dnsConfig: {}
  restartPolicy: Always

  volumes:
  - name: btcd-db
    hostPath:
      type: Directory
      path: {{file_dst_btcd_db_dir}}

status: {}
