---

{{ansible_managed|comment(decoration='#')}}

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: bitcoin-core
  name: pod_bitcoin_core
spec:
  containers:
  - name: bitcoin-core
    image: {{pod_bitcoin_core_registry_address}}/bitcoin-core:{{pod_bitcoin_core_bitcoin_core_version}}
    ports:
{% if (pod_bitcoin_core_bitcoin_core_environment_variables.PORT is defined) %}
    - name: bitcoin-core-network
      containerPort: {{pod_bitcoin_core_bitcoin_core_environment_variables.PORT.rsplit(':', 1)[-1]}}
      hostPort: {{pod_bitcoin_core_bitcoin_core_environment_variables.PORT.rsplit(':', 1)[-1]}}
      protocol: TCP
{% endif %}
{% if (pod_bitcoin_core_bitcoin_core_environment_variables.RPCPORT is defined) %}
    - name: bitcoin-core-rpc
      containerPort: {{pod_bitcoin_core_bitcoin_core_environment_variables.RPCPORT.rsplit(':', 1)[-1]}}
      hostPort: {{pod_bitcoin_core_bitcoin_core_environment_variables.RPCPORT.rsplit(':', 1)[-1]}}
      protocol: TCP
{% endif %}
{% if (pod_bitcoin_core_bitcoin_core_environment_variables.ZMQPUBHASHBLOCK is defined) %}
    - name: bitcoin-core-zmqpubhashblock
      containerPort: {{pod_bitcoin_core_bitcoin_core_environment_variables.ZMQPUBHASHBLOCK.rsplit(':', 1)[-1]}}
      hostPort: {{pod_bitcoin_core_bitcoin_core_environment_variables.ZMQPUBHASHBLOCK.rsplit(':', 1)[-1]}}
      protocol: TCP
{% endif %}
{% if (pod_bitcoin_core_bitcoin_core_environment_variables.ZMQPUBHASHTX is defined) %}
    - name: bitcoin-core-zmqpubhashtx
      containerPort: {{pod_bitcoin_core_bitcoin_core_environment_variables.ZMQPUBHASHTX.rsplit(':', 1)[-1]}}
      hostPort: {{pod_bitcoin_core_bitcoin_core_environment_variables.ZMQPUBHASHTX.rsplit(':', 1)[-1]}}
      protocol: TCP
{% endif %}
{% if (pod_bitcoin_core_bitcoin_core_environment_variables.ZMQPUBRAWBLOCK is defined) %}
    - name: bitcoin-core-zmqpubrawblock
      containerPort: {{pod_bitcoin_core_bitcoin_core_environment_variables.ZMQPUBRAWBLOCK.rsplit(':', 1)[-1]}}
      hostPort: {{pod_bitcoin_core_bitcoin_core_environment_variables.ZMQPUBRAWBLOCK.rsplit(':', 1)[-1]}}
      protocol: TCP
{% endif %}
{% if (pod_bitcoin_core_bitcoin_core_environment_variables.ZMQPUBRAWTX is defined) %}
    - name: bitcoin-core-zmqpubrawtx
      containerPort: {{pod_bitcoin_core_bitcoin_core_environment_variables.ZMQPUBRAWTX.rsplit(':', 1)[-1]}}
      hostPort: {{pod_bitcoin_core_bitcoin_core_environment_variables.ZMQPUBRAWTX.rsplit(':', 1)[-1]}}
      protocol: TCP
{% endif %}
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: {{pod_bitcoin_core_bitcoin_core_read_only_root_filesystem|lower}}
      runAsGroup: 10000
      runAsUser: 10000
      seLinuxOptions:
        type: spc_t
    volumeMounts:
    - name: bitcoin-core-db
      mountPath: /var/local/bitcoin-core/db
    workingDir: /
    env:
{% if not (pod_bitcoin_core_bitcoin_core_environment_variables == {}) %}
{% for key, value in pod_bitcoin_core_bitcoin_core_environment_variables.items() %}
    - name: {{key | upper }}
      value: {{value}}
{% endfor %}
{% endif %}

  dnsConfig: {}
  restartPolicy: Always

  volumes:
  - name: bitcoin-core-db
    hostPath:
      type: Directory
      path: {{file_dst_bitcoin_core_db_dir}}

status: {}
