---

{{ansible_managed|comment(decoration='#')}}

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: bitcoin-core
  name: pod_bitcoin_core
spec:
  containers:
  - name: bitcoin-core
    image: {{pod_bitcoin_core_registry_address}}/bitcoin-core:{{pod_bitcoin_core_bitcoin_core_version}}
    ports:
    - name: bitcoin-core-network
      containerPort: {{pod_bitcoin_core_bitcoin_core_port}}
      hostPort: {{pod_bitcoin_core_bitcoin_core_port}}
      protocol: TCP
{% if (pod_bitcoin_core_bitcoin_core_rest == True) %}
    - name: bitcoin-core-rpc
      containerPort: {{pod_bitcoin_core_bitcoin_core_rpcport}}
      hostPort: {{pod_bitcoin_core_bitcoin_core_rpcport}}
      protocol: TCP
    - name: bitcoin-core-zmqpubhashblock
      containerPort: 5555
      hostPort: 5555
      protocol: TCP
    - name: bitcoin-core-zmqpubhashtx
      containerPort: 5556
      hostPort: 5556
      protocol: TCP
    - name: bitcoin-core-zmqpubrawblock
      containerPort: 5557
      hostPort: 5557
      protocol: TCP
    - name: bitcoin-core-zmqpubrawtx
      containerPort: 5558
      hostPort: 5558
      protocol: TCP
{% endif %}
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: {{pod_bitcoin_core_bitcoin_core_read_only_root_filesystem|lower}}
      runAsGroup: 10000
      runAsUser: 10000
      seLinuxOptions:
        type: spc_t
    volumeMounts:
    - name: bitcoin-core-db
      mountPath: /var/local/bitcoin-core/db
    workingDir: /
    env:
{% if not (pod_bitcoin_core_bitcoin_core_addnode == "") %}
    - name: ADDNODE
      value: "{{pod_bitcoin_core_bitcoin_core_addnode}}"
{% endif %}
{% if not (pod_bitcoin_core_bitcoin_core_bind == "") %}
    - name: BIND
      value: "{{pod_bitcoin_core_bitcoin_core_bind}}"
{% endif %}
{% if not (pod_bitcoin_core_bitcoin_core_datadir == "") %}
    - name: DATADIR
      value: "{{pod_bitcoin_core_bitcoin_core_datadir}}"
{% endif %}
{% if not (pod_bitcoin_core_bitcoin_core_dbcache == "") %}
    - name: DBCACHE
      value: "{{pod_bitcoin_core_bitcoin_core_dbcache}}"
{% endif %}
{% if not (pod_bitcoin_core_bitcoin_core_externalip == "") %}
    - name: EXTERNALIP
      value: "{{pod_bitcoin_core_bitcoin_core_externalip}}"
{% endif %}
{% if not (pod_bitcoin_core_bitcoin_core_maxuploadtarget == "") %}
    - name: MAXUPLOADTARGET
      value: "{{pod_bitcoin_core_bitcoin_core_maxuploadtarget}}"
{% endif %}
{% if not (pod_bitcoin_core_bitcoin_core_onlynet == "") %}
    - name: ONLYNET
      value: "{{pod_bitcoin_core_bitcoin_core_onlynet}}"
{% endif %}
{% if not (pod_bitcoin_core_bitcoin_core_port == "") %}
    - name: PORT
      value: "{{pod_bitcoin_core_bitcoin_core_port}}"
{% endif %}
{% if not (pod_bitcoin_core_bitcoin_core_rest == "") %}
    - name: REST
      value: "{{pod_bitcoin_core_bitcoin_core_rest|lower}}"
{% endif %}
{% if not (pod_bitcoin_core_bitcoin_core_rpcallowip == "") %}
    - name: RPCALLOWIP
      value: "{{pod_bitcoin_core_bitcoin_core_rpcallowip}}"
{% endif %}
{% if not (pod_bitcoin_core_bitcoin_core_rpcauth == "") %}
    - name: RPCAUTH
      value: "{{pod_bitcoin_core_bitcoin_core_rpcauth}}"
{% endif %}
{% if not (pod_bitcoin_core_bitcoin_core_rpcbind == "") %}
    - name: RPCBIND
      value: "{{pod_bitcoin_core_bitcoin_core_rpcbind}}"
{% endif %}
{% if not (pod_bitcoin_core_bitcoin_core_rpcport == "") %}
    - name: RPCPORT
      value: "{{pod_bitcoin_core_bitcoin_core_rpcport}}"
{% endif %}
{% if not (pod_bitcoin_core_bitcoin_core_zmqpubhashblock == "") %}
    - name: ZMQPUBHASHBLOCK
      value: "{{pod_bitcoin_core_bitcoin_core_zmqpubhashblock}}"
{% endif %}
{% if not (pod_bitcoin_core_bitcoin_core_zmqpubhashtx == "") %}
    - name: ZMQPUBHASHTX
      value: "{{pod_bitcoin_core_bitcoin_core_zmqpubhashtx}}"
{% endif %}
{% if not (pod_bitcoin_core_bitcoin_core_zmqpubrawblock == "") %}
    - name: ZMQPUBRAWBLOCK
      value: "{{pod_bitcoin_core_bitcoin_core_zmqpubrawblock}}"
{% endif %}
{% if not (pod_bitcoin_core_bitcoin_core_zmqpubrawtx == "") %}
    - name: ZMQPUBRAWTX
      value: "{{pod_bitcoin_core_bitcoin_core_zmqpubrawtx}}"
{% endif %}

  dnsConfig: {}
  restartPolicy: Always

  volumes:
  - name: bitcoin-core-db
    hostPath:
      type: Directory
      path: {{file_dst_bitcoin_core_db_dir}}

status: {}
