---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - pod_lnd

- name: copy file subuid
  copy:
    src: "{{file_src_subuid}}"
    dest: "{{file_dst_subuid}}"
    mode: "{{file_mode_subuid}}"
    owner: "{{file_owner_subuid}}"
    group: "{{file_group_subuid}}"
  tags:
    - pod_lnd

- name: copy file subgid
  copy:
    src: "{{file_src_subgid}}"
    dest: "{{file_dst_subgid}}"
    mode: "{{file_mode_subgid}}"
    owner: "{{file_owner_subgid}}"
    group: "{{file_group_subgid}}"
  tags:
    - pod_lnd

- name: create group pod_lnd
  group:
    state: present
    name: "{{group_name_pod_lnd}}"
    gid: "{{group_gid_pod_lnd}}"
    system: "{{group_system_pod_lnd}}"
  tags:
    - pod_lnd

- name: create user pod_lnd
  user:
    state: present
    name: "{{user_name_pod_lnd}}"
    comment: "{{user_comment_pod_lnd}}"
    uid: "{{user_uid_pod_lnd}}"
    group: "{{user_group_pod_lnd}}"
    groups: "{{user_groups_pod_lnd}}"
    append: "{{user_append_pod_lnd}}"
    createhome: "{{user_home_create_pod_lnd}}"
    move_home: "{{user_home_move_pod_lnd}}"
    remove: "{{user_home_remove_pod_lnd}}"
    force: "{{user_home_force_pod_lnd}}"
    password: "{{user_password_pod_lnd}}"
    update_password: "{{user_password_update_pod_lnd}}"
    shell: "{{user_shell_pod_lnd}}"
    system: "{{user_system_pod_lnd}}"
  register: register_create_user_pod_lnd
  tags:
    - pod_lnd

- name: loginctl enable-linger
  shell: "{{command_cmd_loginctl_enable_linger}}"
  check_mode: False
  when: register_create_user_pod_lnd.changed
  tags:
    - pod_lnd

- name: create file pod_lnd_etc.dir
  file:
    state: directory
    path: "{{file_dst_pod_lnd_etc_dir}}"
    mode: "{{file_mode_pod_lnd_etc_dir}}"
    owner: "{{file_owner_pod_lnd_etc_dir}}"
    group: "{{file_group_pod_lnd_etc_dir}}"
  tags:
    - pod_lnd

- name: create file opt.dir
  file:
    state: directory
    path: "{{file_dst_opt_dir}}"
    mode: "{{file_mode_opt_dir}}"
    owner: "{{file_owner_opt_dir}}"
    group: "{{file_group_opt_dir}}"
  tags:
    - pod_lnd

- name: create file pod_lnd_opt.dir
  file:
    state: directory
    path: "{{file_dst_pod_lnd_opt_dir}}"
    mode: "{{file_mode_pod_lnd_opt_dir}}"
    owner: "{{file_owner_pod_lnd_opt_dir}}"
    group: "{{file_group_pod_lnd_opt_dir}}"
  tags:
    - pod_lnd

- name: create file lnd_data.dir
  file:
    state: directory
    path: "{{file_dst_lnd_data_dir}}"
    mode: "{{file_mode_lnd_data_dir}}"
    owner: "{{file_owner_lnd_data_dir}}"
    group: "{{file_group_lnd_data_dir}}"
  tags:
    - pod_lnd

- name: create file pod_lnd.service
  template:
    src: "{{file_src_pod_lnd_service}}"
    dest: "{{file_dst_pod_lnd_service}}"
    mode: "{{file_mode_pod_lnd_service}}"
    owner: "{{file_owner_pod_lnd_service}}"
    group: "{{file_group_pod_lnd_service}}"
  tags:
    - pod_lnd

- name: stat file monit.d
  stat:
    path: "{{file_dst_monit_d}}"
  register: register_monit_d
  when: (pod_lnd_monitor_monit_state == True)
  tags:
    - pod_lnd

- name: create file monit.d
  file:
    state: directory
    path: "{{file_dst_monit_d}}"
    mode: "{{file_mode_monit_d}}"
    owner: "{{file_owner_monit_d}}"
    group: "{{file_group_monit_d}}"
  when: (pod_lnd_monitor_monit_state == True) and (register_monit_d.stat.exists == False)
  tags:
    - pod_lnd

- name: check service monit
  shell: "{{command_cmd_check_service_monit}}"
  register: register_check_service_monit
  changed_when: (register_check_service_monit.rc > 1)
  failed_when: (register_check_service_monit.rc > 1)
  check_mode: False
  when: (pod_lnd_monitor_monit_state == True)
  tags:
    - pod_lnd
