---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - pod_lnd

- name: check service pod_lnd
  shell: "{{command_cmd_check_service_pod_lnd}}"
  register: register_check_service_pod_lnd
  changed_when: (register_check_service_pod_lnd.rc == 0)
  failed_when: (register_check_service_pod_lnd.rc > 1)
  check_mode: False
  tags:
    - pod_lnd

- name: stop service pod_lnd
  service:
    state: stopped
    enabled: False
    name: "{{service_name_pod_lnd}}"
    daemon_reload: True
  when: (register_check_service_pod_lnd.rc == 0)
  tags:
    - pod_lnd

- name: remove user pod_lnd
  user:
    state: absent
    name: "{{user_name_pod_lnd}}"
    remove: "{{user_home_remove_pod_lnd}}"
    force: "{{user_home_force_pod_lnd}}"
  tags:
    - pod_lnd

- name: remove group pod_lnd
  group:
    state: absent
    name: "{{group_name_pod_lnd}}"
  tags:
    - pod_lnd

- name: remove file pod_lnd.nft
  file:
    state: absent
    path: "{{file_dst_pod_lnd_nft}}"
  notify: reload service nftables
  tags:
    - pod_lnd

- name: remove file pod_lnd-lnd.cfg
  file:
    state: absent
    path: "{{file_dst_pod_lnd_lnd_cfg}}"
  notify: reload service monit
  tags:
    - pod_lnd

- name: remove file pod_lnd_etc.dir
  file:
    state: absent
    path: "{{file_dst_pod_lnd_etc_dir}}"
  tags:
    - pod_lnd

- name: remove file pod_lnd.default
  file:
    state: absent
    path: "{{file_dst_pod_lnd_default}}"
  tags:
    - pod_lnd

- name: remove file pod_lnd.service
  file:
    state: absent
    path: "{{file_dst_pod_lnd_service}}"
  tags:
    - pod_lnd
