---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'

- name: reload service monit
  service:
    state: reloaded
    name: "{{service_name_monit}}"
  when: (register_check_service_monit.rc == 0)

- name: reload service blockbook
  service:
    state: reloaded
    name: "{{service_name_blockbook}}"

- name: restart service blockbook
  service:
    state: restarted
    name: "{{service_name_blockbook}}"
