---

{{ansible_managed|comment(decoration='#')}}

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: rusty-kaspa
  name: pod_rusty_kaspa
spec:
  containers:
  - name: rusty-kaspa
    image: {{pod_rusty_kaspa_registry_address}}/rusty-kaspa:{{pod_rusty_kaspa_rusty_kaspa_version}}
    ports:
    - name: pod_rusty_kaspa-grpc
      containerPort: 16110
      hostPort: 16110
      protocol: TCP
    - name: pod_rusty_kaspa-network
      containerPort: 16111
      hostPort: 16111
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: {{pod_rusty_kaspa_rusty_kaspa_read_only_root_filesystem|lower}}
      runAsGroup: 10000
      runAsUser: 10000
      seLinuxOptions:
        type: spc_t
    volumeMounts:
    - name: rusty-kaspa-data
      mountPath: /var/local/rusty-kaspa/data
    - name: rusty-kaspa-tmp
      mountPath: /tmp/rusty-kaspa
    workingDir: /
    env:
{% if not (pod_rusty_kaspa_rusty_kaspa_environment_variables == {}) %}
{% for key, value in pod_rusty_kaspa_rusty_kaspa_environment_variables.items() %}
    - name: {{key | upper }}
      value: {{value}}
{% endfor %}
{% endif %}

  dnsConfig: {}
  restartPolicy: Always

  volumes:
  - name: rusty-kaspa-data
    hostPath:
      type: Directory
      path: {{file_dst_pod_rusty_kaspa_data_dir}}

  - name: rusty-kaspa-tmp
    hostPath:
      type: Directory
      path: {{file_dst_pod_rusty_kaspa_tmp_dir}}

status: {}
