---

{{ansible_managed|comment(decoration='#')}}

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: lightning
  name: pod_lightning
spec:
  containers:
  - name: lightning
    image: {{pod_lightning_registry_address}}/lightning:{{pod_lightning_lightning_version}}
    ports:
{% if (pod_lightning_lightning_environment_variables.ANNOUNCE_ADDR_DISCOVERED_PORT is defined) %}
    - name: lightning-network
      containerPort: {{pod_lightning_lightning_environment_variables.ANNOUNCE_ADDR_DISCOVERED_PORT.rsplit(':', 1)[-1]}}
      hostPort: {{pod_lightning_lightning_environment_variables.ANNOUNCE_ADDR_DISCOVERED_PORT.rsplit(':', 1)[-1]}}
      protocol: TCP
{% endif %}
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: {{pod_lightning_lightning_read_only_root_filesystem|lower}}
      runAsGroup: 10000
      runAsUser: 10000
      seLinuxOptions:
        type: spc_t
    volumeMounts:
    - name: lightning-data
      mountPath: /var/local/lightning/data
    workingDir: /
    env:
{% if not (pod_lightning_lightning_environment_variables == {}) %}
{% for key, value in pod_lightning_lightning_environment_variables.items() %}
    - name: {{key|upper}}
      value: {{value}}
{% endfor %}
{% endif %}

  dnsConfig: {}
  restartPolicy: Always

  volumes:
  - name: lightning-data
    hostPath:
      type: Directory
      path: {{file_dst_lightning_data_dir}}

status: {}
