---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - pod_btcd

- name: create file pod_btcd.yaml
  template:
    src: "{{file_src_pod_btcd_yaml}}"
    dest: "{{file_dst_pod_btcd_yaml}}"
    mode: "{{file_mode_pod_btcd_yaml}}"
    owner: "{{file_owner_pod_btcd_yaml}}"
    group: "{{file_group_pod_btcd_yaml}}"
  notify: restart service pod_btcd
  tags:
    - pod_btcd

- name: create file pod_btcd.default
  template:
    src: "{{file_src_pod_btcd_default}}"
    dest: "{{file_dst_pod_btcd_default}}"
    mode: "{{file_mode_pod_btcd_default}}"
    owner: "{{file_owner_pod_btcd_default}}"
    group: "{{file_group_pod_btcd_default}}"
  notify: restart service pod_btcd
  tags:
    - pod_btcd

- name: create file pod_btcd-btcd.cfg
  template:
    src: "{{file_src_pod_btcd_btcd_cfg}}"
    dest: "{{file_dst_pod_btcd_btcd_cfg}}"
    mode: "{{file_mode_pod_btcd_btcd_cfg}}"
    owner: "{{file_owner_pod_btcd_btcd_cfg}}"
    group: "{{file_group_pod_btcd_btcd_cfg}}"
  notify:
    - validate monit
    - reload monit
  when: (pod_btcd_monitor_monit_state == True)
  tags:
    - pod_btcd

- name: remove file pod_btcd-btcd.cfg
  file:
    state: absent
    path: "{{file_dst_pod_btcd_btcd_cfg}}"
  notify: reload monit
  when: (pod_btcd_monitor_monit_state == False)
  tags:
    - pod_btcd

- name: create file pod_btcd.nft
  template:
    src: "{{file_src_pod_btcd_nft}}"
    dest: "{{file_dst_pod_btcd_nft}}"
    mode: "{{file_mode_pod_btcd_nft}}"
    owner: "{{file_owner_pod_btcd_nft}}"
    group: "{{file_group_pod_btcd_nft}}"
  notify:
    - validate nftables
    - reload nftables
  when: (pod_btcd_nftables_state == True)
  tags:
    - pod_btcd

- name: remove file pod_btcd.nft
  file:
    state: absent
    path: "{{file_dst_pod_btcd_nft}}"
  notify: reload nftables
  when: (pod_btcd_nftables_state == False)
  tags:
    - pod_btcd

- name: start service pod_btcd
  service:
    state: started
    enabled: True
    name: "{{service_name_pod_btcd}}"
    daemon_reload: True
  tags:
    - pod_btcd
