---

- name: include variables
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_distribution_major_version}}.yml"
      - 'vars/main.yml'
      errors: 'ignore'
  tags:
    - bitcoin_core

- name: create file bitcoind.default
  template:
    src: "{{file_src_bitcoind_default}}"
    dest: "{{file_dst_bitcoind_default}}"
    mode: "{{file_mode_bitcoind_default}}"
    owner: "{{file_owner_bitcoind_default}}"
    group: "{{file_group_bitcoind_default}}"
  notify: restart service bitcoind
  tags:
    - bitcoin_core

- name: create file bitcoin.conf
  template:
    src: "{{file_src_bitcoin_conf}}"
    dest: "{{file_dst_bitcoin_conf}}"
    mode: "{{file_mode_bitcoin_conf}}"
    owner: "{{file_owner_bitcoin_conf}}"
    group: "{{file_group_bitcoin_conf}}"
  notify: restart service bitcoind
  tags:
    - bitcoin_core

- name: create file bitcoind.cfg
  template:
    src: "{{file_src_bitcoind_cfg}}"
    dest: "{{file_dst_bitcoind_cfg}}"
    mode: "{{file_mode_bitcoind_cfg}}"
    owner: "{{file_owner_bitcoind_cfg}}"
    group: "{{file_group_bitcoind_cfg}}"
  notify: reload service monit
  when: (bitcoin_core_monitor_monit_state is match('true|yes|enable'))
  tags:
    - bitcoin_core

- name: start service bitcoind
  service:
    state: 'started'
    enabled: 'yes'
    name: "{{service_name_bitcoind}}"
  tags:
    - bitcoin_core
