---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - bitcoin_core

- name: install package tar
  package:
    state: present
    name: "{{package_name_tar}}"
    install_recommends: False
  tags:
    - bitcoin_core

- name: create group bitcoind
  group:
    state: present
    name: "{{group_name_bitcoind}}"
    system: "{{group_system_bitcoind}}"
  tags:
    - bitcoin_core

- name: create user bitcoind
  user:
    state: present
    name: "{{user_name_bitcoind}}"
    comment: "{{user_comment_bitcoind}}"
    group: "{{user_group_bitcoind}}"
    append: "{{user_append_bitcoind}}"
    createhome: "{{user_home_create_bitcoind}}"
    move_home: "{{user_home_move_bitcoind}}"
    remove: "{{user_home_remove_bitcoind}}"
    force: "{{user_home_force_bitcoind}}"
    password: "{{user_password_bitcoind}}"
    update_password: "{{user_password_update_bitcoind}}"
    shell: "{{user_shell_bitcoind}}"
    system: "{{user_system_bitcoind}}"
  tags:
    - bitcoin_core

- name: create file app.dir
  file:
    state: directory
    path: "{{file_dst_app_dir}}"
    mode: "{{file_mode_app_dir}}"
    owner: "{{file_owner_app_dir}}"
    group: "{{file_group_app_dir}}"
  tags:
    - bitcoin_core

- name: create file bitcoind_app.dir
  file:
    state: directory
    path: "{{file_dst_bitcoind_app_dir}}"
    mode: "{{file_mode_bitcoind_app_dir}}"
    owner: "{{file_owner_bitcoind_app_dir}}"
    group: "{{file_group_bitcoind_app_dir}}"
  tags:
    - bitcoin_core

- name: create file data.dir
  file:
    state: directory
    path: "{{file_dst_data_dir}}"
    mode: "{{file_mode_data_dir}}"
    owner: "{{file_owner_data_dir}}"
    group: "{{file_group_data_dir}}"
  tags:
    - bitcoin_core

- name: create file bitcoind_data.dir
  file:
    state: directory
    path: "{{file_dst_bitcoind_data_dir}}"
    mode: "{{file_mode_bitcoind_data_dir}}"
    owner: "{{file_owner_bitcoind_data_dir}}"
    group: "{{file_group_bitcoind_data_dir}}"
  tags:
    - bitcoin_core

- name: create file bitcoind_log.dir
  file:
    state: directory
    path: "{{file_dst_bitcoind_log_dir}}"
    mode: "{{file_mode_bitcoind_log_dir}}"
    owner: "{{file_owner_bitcoind_log_dir}}"
    group: "{{file_group_bitcoind_log_dir}}"
  tags:
    - bitcoin_core

- name: create file bitcoind_src.dir
  file:
    state: directory
    path: "{{file_dst_bitcoind_src_dir}}"
    mode: "{{file_mode_bitcoind_src_dir}}"
    owner: "{{file_owner_bitcoind_src_dir}}"
    group: "{{file_group_bitcoind_src_dir}}"
  tags:
    - bitcoin_core

- name: download file bitcoin-core.tar.gz
  get_url:
    url: "{{file_src_bitcoin_core_tar_gz}}"
    dest: "{{file_dst_bitcoin_core_tar_gz}}"
    mode: "{{file_mode_bitcoin_core_tar_gz}}"
    owner: "{{file_owner_bitcoin_core_tar_gz}}"
    group: "{{file_group_bitcoin_core_tar_gz}}"
    checksum: "{{file_checksum_bitcoin_core_tar_gz}}"
  tags:
    - bitcoin_core

- name: unarchive file bitcoin-core.tar.gz
  unarchive:
    src: "{{file_src_bitcoin_core}}"
    dest: "{{file_dst_bitcoin_core}}"
    owner: "{{file_owner_bitcoin_core}}"
    group: "{{file_group_bitcoin_core}}"
    creates: "{{file_creates_bitcoin_core}}"
    remote_src: True
  tags:
    - bitcoin_core

- name: create file bitcoin-current.link
  file:
    state: link
    src: "{{file_src_bitcoin_current_link}}"
    path: "{{file_dst_bitcoin_current_link}}"
    owner: "{{file_owner_bitcoin_current_link}}"
    group: "{{file_group_bitcoin_current_link}}"
  tags:
    - bitcoin_core

- name: create file debug.log
  copy:
    content: ''
    force: False
    dest: "{{file_dst_debug_log}}"
    mode: "{{file_mode_debug_log}}"
    owner: "{{file_owner_debug_log}}"
    group: "{{file_group_debug_log}}"
  tags:
    - bitcoin_core

- name: create file bitcoind_conf.dir
  file:
    state: directory
    path: "{{file_dst_bitcoind_conf_dir}}"
    mode: "{{file_mode_bitcoind_conf_dir}}"
    owner: "{{file_owner_bitcoind_conf_dir}}"
    group: "{{file_group_bitcoind_conf_dir}}"
  tags:
    - bitcoin_core

- name: create file bitcoind.service
  template:
    src: "{{file_src_bitcoind_service}}"
    dest: "{{file_dst_bitcoind_service}}"
    mode: "{{file_mode_bitcoind_service}}"
    owner: "{{file_owner_bitcoind_service}}"
    group: "{{file_group_bitcoind_service}}"
  tags:
    - bitcoin_core

- name: stat file monit.d
  stat:
    path: "{{file_dst_monit_d}}"
  register: register_monit_d
  when: (bitcoin_core_monitor_monit_state == True)
  tags:
    - bitcoin_core

- name: create file monit.d
  file:
    state: directory
    path: "{{file_dst_monit_d}}"
    mode: "{{file_mode_monit_d}}"
    owner: "{{file_owner_monit_d}}"
    group: "{{file_group_monit_d}}"
  when: (bitcoin_core_monitor_monit_state == True) and (register_monit_d.stat.exists == False)
  tags:
    - bitcoin_core

- name: check service monit
  shell: "{{command_cmd_check_service_monit}}"
  register: register_check_service_monit
  changed_when: (register_check_service_monit.rc > 1)
  failed_when: (register_check_service_monit.rc > 1)
  check_mode: False
  when: (bitcoin_core_monitor_monit_state == True)
  tags:
    - bitcoin_core
