---

- name: include variables
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_distribution_major_version}}.yml"
      - 'vars/main.yml'
      errors: 'ignore'
  tags:
    - bitcoin_core

- name: remove user bitcoind
  user:
    state: 'absent'
    name: "{{user_name_bitcoind}}"
    remove: "{{user_home_remove_bitcoind}}"
    force: "{{user_home_force_bitcoind}}"
  tags:
    - bitcoin_core

- name: remove group bitcoind
  group:
    state: 'absent'
    name: "{{group_name_bitcoind}}"
  tags:
    - bitcoin_core

- name: remove file bitcoind.cfg
  file:
    state: 'absent'
    path: "{{file_dst_bitcoind_cfg}}"
  notify: reload service monit
  tags:
    - bitcoin_core

- name: remove file bitcoind.service
  file:
    state: 'absent'
    path: "{{file_dst_bitcoind_service}}"
  tags:
    - bitcoin_core

- name: remove file bitcoind.default
  file:
    state: 'absent'
    path: "{{file_dst_bitcoind_default}}"
  tags:
    - bitcoin_core

- name: remove file bitcoind_app.dir
  file:
    state: 'absent'
    path: "{{file_dst_bitcoind_src_dir}}"
  tags:
    - bitcoin_core

- name: remove file bitcoind_src.dir
  file:
    state: 'absent'
    path: "{{file_dst_bitcoind_src_dir}}"
  tags:
    - bitcoin_core
