---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - pod_rusty_kaspa

- name: check service pod_rusty_kaspa
  shell: "{{command_cmd_check_service_pod_rusty_kaspa}}"
  register: register_check_service_pod_rusty_kaspa
  changed_when: (register_check_service_pod_rusty_kaspa.rc == 0)
  failed_when: (register_check_service_pod_rusty_kaspa.rc > 1)
  check_mode: False
  tags:
    - pod_rusty_kaspa

- name: stop service pod_rusty_kaspa
  service:
    state: stopped
    enabled: False
    name: "{{service_name_pod_rusty_kaspa}}"
    daemon_reload: True
  when: (register_check_service_pod_rusty_kaspa.rc == 0)
  tags:
    - pod_rusty_kaspa

- name: remove file pod_rusty_kaspa.nft
  file:
    state: absent
    path: "{{file_dst_pod_rusty_kaspa_nft}}"
  notify: reload nftables
  tags:
    - pod_rusty_kaspa

- name: remove file pod_rusty_kaspa-rusty_kaspa.cfg
  file:
    state: absent
    path: "{{file_dst_pod_rusty_kaspa_rusty_kaspa_cfg}}"
  notify: reload monit
  tags:
    - pod_rusty_kaspa

- name: remove file pod_rusty_kaspa_etc.dir
  file:
    state: absent
    path: "{{file_dst_pod_rusty_kaspa_etc_dir}}"
  tags:
    - pod_rusty_kaspa

- name: remove file pod_rusty_kaspa_tmp.dir
  file:
    state: absent
    path: "{{file_dst_pod_rusty_kaspa_tmp_dir}}"
  tags:
    - pod_rusty_kaspa

- name: remove file pod_rusty_kaspa.default
  file:
    state: absent
    path: "{{file_dst_pod_rusty_kaspa_default}}"
  tags:
    - pod_rusty_kaspa

- name: remove file pod_rusty_kaspa.service
  file:
    state: absent
    path: "{{file_dst_pod_rusty_kaspa_service}}"
  tags:
    - pod_rusty_kaspa
