---

{{ansible_managed|comment(decoration='#')}}

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: lnd
  name: pod_lnd
spec:
  containers:
  - name: lnd
    image: {{pod_lnd_registry_address}}/lnd:{{pod_lnd_lnd_version}}
    ports:
{% if (pod_lnd_lnd_environment_variables.LISTEN is defined) %}
    - name: lnd-network
      containerPort: {{pod_lnd_lnd_environment_variables.LISTEN.rsplit(':', 1)[-1]}}
      hostPort: {{pod_lnd_lnd_environment_variables.LISTEN.rsplit(':', 1)[-1]}}
      protocol: TCP
{% endif %}
{% if (pod_lnd_lnd_environment_variables.RESTLISTEN is defined) %}
    - name: lnd-rest
      containerPort: {{pod_lnd_lnd_environment_variables.RESTLISTEN.rsplit(':', 1)[-1]}}
      hostPort: {{pod_lnd_lnd_environment_variables.RESTLISTEN.rsplit(':', 1)[-1]}}
      protocol: TCP
{% endif %}
{% if (pod_lnd_lnd_environment_variables.RPCLISTEN is defined) %}
    - name: lnd-rpc
      containerPort: {{pod_lnd_lnd_environment_variables.RPCLISTEN.rsplit(':', 1)[-1]}}
      hostPort: {{pod_lnd_lnd_environment_variables.RPCLISTEN.rsplit(':', 1)[-1]}}
      protocol: TCP
{% endif %}
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: {{pod_lnd_lnd_read_only_root_filesystem|lower}}
      runAsGroup: 10000
      runAsUser: 10000
      seLinuxOptions:
        type: spc_t
    volumeMounts:
    - name: lnd-data
      mountPath: /var/local/lnd/data
    workingDir: /
    env:
{% if not (pod_lnd_lnd_environment_variables == {}) %}
{% for key, value in pod_lnd_lnd_environment_variables.items() %}
    - name: {{key | upper }}
      value: {{value}}
{% endfor %}
{% endif %}

  dnsConfig: {}
  restartPolicy: Always

  volumes:
  - name: lnd-data
    hostPath:
      type: Directory
      path: {{file_dst_lnd_data_dir}}

status: {}
