---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - blockbook

- name: create file blockbook.default
  template:
    src: "{{file_src_blockbook_default}}"
    dest: "{{file_dst_blockbook_default}}"
    mode: "{{file_mode_blockbook_default}}"
    owner: "{{file_owner_blockbook_default}}"
    group: "{{file_group_blockbook_default}}"
  tags:
    - blockbook

- name: create file blockbook.json
  template:
    src: "{{file_src_blockbook_json}}"
    dest: "{{file_dst_blockbook_json}}"
    mode: "{{file_mode_blockbook_json}}"
    owner: "{{file_owner_blockbook_json}}"
    group: "{{file_group_blockbook_json}}"
  tags:
    - blockbook

- name: remove file blockbook.cfg
  file:
    state: absent
    path: "{{file_dst_blockbook_cfg}}"
  notify: reload monit
  tags:
    - blockbook

- name: create file blockbook.nft
  template:
    src: "{{file_src_blockbook_nft}}"
    dest: "{{file_dst_blockbook_nft}}"
    mode: "{{file_mode_blockbook_nft}}"
    owner: "{{file_owner_blockbook_nft}}"
    group: "{{file_group_blockbook_nft}}"
  notify:
    - validate nftables
    - reload nftables
  when: (blockbook_nftables_state == True)
  tags:
    - blockbook

- name: remove file blockbook.nft
  file:
    state: absent
    path: "{{file_dst_blockbook_nft}}"
  notify: reload nftables
  when: (blockbook_nftables_state == False)
  tags:
    - blockbook

- name: stop service blockbook
  service:
    state: stopped
    enabled: False
    name: "{{service_name_blockbook}}"
    daemon_reload: True
  tags:
    - blockbook
