---

- name: assert operating system family and version
  block:

    - name: import tasks install
      import_tasks: install.yml
      when: not (blockbook_state is match('false|no|remove|quiesce|inactive'))
      tags:
        - blockbook

    - name: import tasks enable
      import_tasks: enable.yml
      when: (blockbook_state is match('start|on|enable'))
      tags:
        - blockbook

    - name: import tasks disable
      import_tasks: disable.yml
      when: (blockbook_state is match('stop|off|disable'))
      tags:
        - blockbook

    - name: import tasks remove
      import_tasks: remove.yml
      when: (blockbook_state is match('false|no|remove'))
      tags:
        - blockbook

  when: ((ansible_os_family == 'Debian') and (ansible_distribution_major_version is match('11|12')))
  tags:
    - blockbook
