---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - pod_kasvault

- name: check service pod_kasvault
  shell: "{{command_cmd_check_service_pod_kasvault}}"
  register: register_check_service_pod_kasvault
  changed_when: (register_check_service_pod_kasvault.rc == 0)
  failed_when: (register_check_service_pod_kasvault.rc > 1)
  check_mode: False
  tags:
    - pod_kasvault

- name: stop service pod_kasvault
  service:
    state: stopped
    enabled: False
    name: "{{service_name_pod_kasvault}}"
    daemon_reload: True
  when: (register_check_service_pod_kasvault.rc == 0)
  tags:
    - pod_kasvault

- name: remove file pod_kasvault.nft
  file:
    state: absent
    path: "{{file_dst_pod_kasvault_nft}}"
  notify: reload nftables
  tags:
    - pod_kasvault

- name: remove file pod_kasvault-pod_kasvault.cfg
  file:
    state: absent
    path: "{{file_dst_pod_kasvault_kasvault_cfg}}"
  notify: reload monit
  tags:
    - pod_kasvault

- name: remove file pod_kasvault_etc.dir
  file:
    state: absent
    path: "{{file_dst_pod_kasvault_etc_dir}}"
  tags:
    - pod_kasvault

- name: remove file pod_kasvault.default
  file:
    state: absent
    path: "{{file_dst_pod_kasvault_default}}"
  tags:
    - pod_kasvault

- name: remove file pod_kasvault.service
  file:
    state: absent
    path: "{{file_dst_pod_kasvault_service}}"
  tags:
    - pod_kasvault
