---

- name: include variables
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_distribution_major_version}}.yml"
      - 'vars/main.yml'
      errors: 'ignore'

- name: systemctl daemon-reload
  command: "{{command_cmd_systemctl_daemon_reload}}"

- name: reload service monit
  service:
    state: 'reloaded'
    name: "{{service_name_monit}}"
  when: (register_check_service_monit.rc == 0)

- name: reload service lnd
  service:
    state: 'reloaded'
    name: "{{service_name_lnd}}"

- name: restart service lnd
  service:
    state: 'restarted'
    name: "{{service_name_lnd}}"
