---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - pod_lightning

- name: create file pod_lightning.yaml
  template:
    src: "{{file_src_pod_lightning_yaml}}"
    dest: "{{file_dst_pod_lightning_yaml}}"
    mode: "{{file_mode_pod_lightning_yaml}}"
    owner: "{{file_owner_pod_lightning_yaml}}"
    group: "{{file_group_pod_lightning_yaml}}"
  tags:
    - pod_lightning

- name: create file pod_lightning.default
  template:
    src: "{{file_src_pod_lightning_default}}"
    dest: "{{file_dst_pod_lightning_default}}"
    mode: "{{file_mode_pod_lightning_default}}"
    owner: "{{file_owner_pod_lightning_default}}"
    group: "{{file_group_pod_lightning_default}}"
  tags:
    - pod_lightning

- name: remove file pod_lightning-lightning.cfg
  file:
    state: absent
    path: "{{file_dst_pod_lightning_lightning_cfg}}"
  notify: reload service monit
  tags:
    - pod_lightning

- name: create file pod_lightning.nft
  template:
    src: "{{file_src_pod_lightning_nft}}"
    dest: "{{file_dst_pod_lightning_nft}}"
    mode: "{{file_mode_pod_lightning_nft}}"
    owner: "{{file_owner_pod_lightning_nft}}"
    group: "{{file_group_pod_lightning_nft}}"
  notify: reload service nftables
  when: (pod_lightning_nftables_state == True)
  tags:
    - pod_lightning

- name: remove file pod_lightning.nft
  file:
    state: absent
    path: "{{file_dst_pod_lightning_nft}}"
  notify: reload service nftables
  when: (pod_lightning_nftables_state == False)
  tags:
    - pod_lightning

- name: stop service pod_lightning
  service:
    state: stopped
    enabled: False
    name: "{{service_name_pod_lightning}}"
    daemon_reload: True
  tags:
    - pod_lightning
