---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - pod_lightning

- name: create file pod_lightning_etc.dir
  file:
    state: directory
    path: "{{file_dst_pod_lightning_etc_dir}}"
    mode: "{{file_mode_pod_lightning_etc_dir}}"
    owner: "{{file_owner_pod_lightning_etc_dir}}"
    group: "{{file_group_pod_lightning_etc_dir}}"
  tags:
    - pod_lightning

- name: create file opt.dir
  file:
    state: directory
    path: "{{file_dst_opt_dir}}"
    mode: "{{file_mode_opt_dir}}"
    owner: "{{file_owner_opt_dir}}"
    group: "{{file_group_opt_dir}}"
  tags:
    - pod_lightning

- name: create file pod_lightning_opt.dir
  file:
    state: directory
    path: "{{file_dst_pod_lightning_opt_dir}}"
    mode: "{{file_mode_pod_lightning_opt_dir}}"
    owner: "{{file_owner_pod_lightning_opt_dir}}"
    group: "{{file_group_pod_lightning_opt_dir}}"
  tags:
    - pod_lightning

- name: create file lightning_data.dir
  file:
    state: directory
    path: "{{file_dst_lightning_data_dir}}"
    mode: "{{file_mode_lightning_data_dir}}"
    owner: "{{file_owner_lightning_data_dir}}"
    group: "{{file_group_lightning_data_dir}}"
  tags:
    - pod_lightning

- name: create file pod_lightning.service
  template:
    src: "{{file_src_pod_lightning_service}}"
    dest: "{{file_dst_pod_lightning_service}}"
    mode: "{{file_mode_pod_lightning_service}}"
    owner: "{{file_owner_pod_lightning_service}}"
    group: "{{file_group_pod_lightning_service}}"
  tags:
    - pod_lightning

- name: stat file monit.d
  stat:
    path: "{{file_dst_monit_d}}"
  register: register_monit_d
  when: (pod_lightning_monitor_monit_state == True)
  tags:
    - pod_lightning

- name: create file monit.d
  file:
    state: directory
    path: "{{file_dst_monit_d}}"
    mode: "{{file_mode_monit_d}}"
    owner: "{{file_owner_monit_d}}"
    group: "{{file_group_monit_d}}"
  when: (pod_lightning_monitor_monit_state == True) and (register_monit_d.stat.exists == False)
  tags:
    - pod_lightning

- name: stat file nftables.d
  stat:
    path: "{{file_dst_nftables_d}}"
  register: register_nftables_d
  when: (pod_lightning_nftables_state == True)
  tags:
    - pod_lightning

- name: create file nftables.d
  file:
    state: directory
    path: "{{file_dst_nftables_d}}"
    mode: "{{file_mode_nftables_d}}"
    owner: "{{file_owner_nftables_d}}"
    group: "{{file_group_nftables_d}}"
  when: (pod_lightning_nftables_state == True) and (register_nftables_d.stat.exists == False)
  tags:
    - pod_lightning
